#!/bin/sh
# Remove deepseek-harness-remote-node from a dsh host, a node, or both.
#
# The mirror of install-host.sh and install-node.sh. Both installers ONLY add
# things, and this removes ONLY those things: every file it deletes and every
# line it strips is marked by the installer that wrote it. Nothing is guessed
# at, and a config file it does not recognise is left alone rather than
# rewritten on a hope.
#
# Usage:
#   ./uninstall.sh [options]
#
#   --host             Only undo the host install (the plugin + config entries)
#   --node             Only undo the node install (the command + cached source)
#   --dsh-home DIR     dsh home (default: $DSH_HOME, else ~/.dsh)
#   --bin-dir DIR      Where the `dsh-node` command was installed
#   --purge-workspace  ALSO delete the node's working directory. Off by default
#                      and never implied: it holds whatever the agent wrote
#                      there, which is the user's data, not ours.
#   --dry-run          Print what would happen, change nothing
#   -h, --help         Show this help
#
# With neither --host nor --node, both are attempted and each is skipped when
# nothing of it is present.
#
# Exit status:
#   0  done (including "nothing to do")
#   1  something was present but could not be removed
set -eu

DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
BIN_DIR=""
DO_HOST=0
DO_NODE=0
PURGE_WORKSPACE=0
DRY_RUN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --host) DO_HOST=1; shift ;;
    --node) DO_NODE=1; shift ;;
    --dsh-home) DSH_HOME="$2"; shift 2 ;;
    --bin-dir) BIN_DIR="$2"; shift 2 ;;
    --purge-workspace) PURGE_WORKSPACE=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help)
      sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "uninstall: unknown argument: $1" >&2; exit 2 ;;
  esac
done

# Neither named: undo whatever is actually present, so the common case needs no
# flags. Both flags at once is explicit and is honoured as given.
AUTO=0
if [ "$DO_HOST" -eq 0 ] && [ "$DO_NODE" -eq 0 ]; then
  AUTO=1
  DO_HOST=1
  DO_NODE=1
fi

PROFILE_DIR="$DSH_HOME/profiles/web"
SCOPE_DIR="$PROFILE_DIR/node_modules/@shaowenchen"
LINK_PATH="$SCOPE_DIR/deepseek-harness-remote-node"
PATCH_FILE="$PROFILE_DIR/cordis.patch.yml"
CACHE_DIR="${DSH_NODE_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/deepseek-harness-remote-node}"
if [ -z "$BIN_DIR" ]; then
  if [ -x /usr/local/bin/dsh-node ] || [ -w /usr/local/bin ] 2>/dev/null; then
    BIN_DIR=/usr/local/bin
  else
    BIN_DIR="$HOME/.local/bin"
  fi
fi
WRAPPER="$BIN_DIR/dsh-node"
WORKSPACE_DIR="$HOME/.deepseek-harness-remote-node"

say() { printf '%s\n' "$*"; }
act() { if [ "$DRY_RUN" -eq 1 ]; then say "  would: $*"; else say "  $*"; fi; }
die() { echo "uninstall: $*" >&2; exit 1; }

# The two lines install-node.sh writes into the wrapper it generates. Matching
# them is what distinguishes OUR wrapper from a file the user wrote or that an
# earlier layout left behind — deleting either of those would be destroying
# something we did not create.
WRAPPER_SIG='Generated by deepseek-harness-remote-node'
is_our_wrapper() {
  [ -f "$1" ] && grep -qF "$WRAPPER_SIG" "$1" 2>/dev/null
}

# ── host ─────────────────────────────────────────────────────────────────────
#
# The patch file is the delicate part. It is YAML that the operator may have
# added their own entries to, and it carries a dsh-generated header we must not
# disturb. So the removal is marker-driven: each block install-host.sh writes
# begins with a comment this script recognises, and everything from that comment
# to the end of that block is ours.
#
# The rewrite is done with awk into a temporary file that is moved into place
# only after awk exits successfully, so an interrupted run leaves the original
# intact rather than a half-written config.
strip_our_blocks() {
  awk '
    # Modes: 0 normal, 1 insert block, 2 disable block, 3 credential backfill.
    BEGIN { mode = 0 }

    /^# ── remote node execution world \(added by scripts\/install-host\.sh\) ──$/ {
      mode = 1; dropped = 1; next
    }
    /^# ── host execution world disabled \(scripts\/install-host\.sh\) ──$/ {
      mode = 2; dropped = 1; next
    }
    /^# Credential verification, added to the node-registry entry above\.$/ {
      mode = 3; dropped = 1; next
    }

    # Inside one of our blocks: drop its comment lines and its blank separators.
    mode != 0 && /^#/ { next }
    mode != 0 && /^[[:space:]]*$/ { next }

    # Drop the YAML entries each block consists of. Anything that is not one of
    # them ends the block, so an operator entry that follows ours survives.
    mode == 1 && /^- insert:[[:space:]]*$/ { next }
    mode == 1 && /^[[:space:]]+/ { next }
    mode == 2 && /^- id: (fs-sandbox|subprocess)[[:space:]]*$/ { next }
    mode == 2 && /^[[:space:]]+disabled: true[[:space:]]*$/ { next }
    mode == 3 && /^- id: node-registry[[:space:]]*$/ { next }
    mode == 3 && /^[[:space:]]+config:[[:space:]]*$/ { next }
    mode == 3 && /^[[:space:]]+credential:/ { next }

    { mode = 0; print }
  ' "$1"
  return $?
}

uninstall_host() {
  found=0
  [ -L "$LINK_PATH" ] || [ -e "$LINK_PATH" ] && found=1
  [ -f "$PATCH_FILE" ] && grep -q 'install-host.sh' "$PATCH_FILE" 2>/dev/null && found=1

  if [ "$found" -eq 0 ]; then
    say "host: nothing installed — skipped"
    return 0
  fi
  [ "$AUTO" -eq 1 ] && say "host:"
  say "[host] removing the plugin and its configuration"

  # 1. The link. A symlink is ours to remove; a real directory is not — that is
  #    someone else's checkout and deleting it would be destroying data.
  if [ -L "$LINK_PATH" ]; then
    act "remove symlink $LINK_PATH"
    if [ "$DRY_RUN" -eq 0 ]; then rm -f "$LINK_PATH"; fi
  elif [ -e "$LINK_PATH" ]; then
    say "  !! $LINK_PATH is a real directory, not a symlink — left alone."
    say "     Remove it yourself if it is a stale copy:"
    say "       rm -rf $LINK_PATH"
  fi
  # The scope directory is ours only when it is now empty.
  if [ -d "$SCOPE_DIR" ] && [ "$DRY_RUN" -eq 0 ]; then rmdir "$SCOPE_DIR" 2>/dev/null || true; fi

  # 2. The patch entries.
  if [ -f "$PATCH_FILE" ] && grep -q 'install-host.sh' "$PATCH_FILE" 2>/dev/null; then
    tmp="$PATCH_FILE.tmp.$$"
    if [ "$DRY_RUN" -eq 1 ]; then
      say "  would: strip the insert, disable, and credential blocks from $PATCH_FILE"
      say "         (keeping dsh's header and any entries you added)"
    else
      if strip_our_blocks "$PATCH_FILE" > "$tmp"; then
        # Drop trailing blank lines so a file whose only additions were ours
        # comes back byte-identical rather than one newline longer.
        awk 'NF { last = NR } { line[NR] = $0 } END { for (i = 1; i <= last; i++) print line[i] }' "$tmp" > "$tmp.trim" && mv "$tmp.trim" "$tmp"
        # A patch file that is now empty except comments and `[]` is restored to
        # dsh's own seed, so the profile is left exactly as dsh made it.
        if [ -z "$(sed 's/#.*//' "$tmp" | tr -d '[:space:]' | sed 's/\[\]//')" ]; then
          { grep '^#' "$tmp" 2>/dev/null || true; printf '[]\n'; } > "$PATCH_FILE"
          act "stripped $PATCH_FILE (restored to dsh's empty seed)"
        else
          mv "$tmp" "$PATCH_FILE"
          act "stripped $PATCH_FILE"
        fi
      else
        rm -f "$tmp"
        say "  !! could not rewrite $PATCH_FILE — left untouched"
        return 1
      fi
    fi
  fi

  say ""
  say "  RESTART dsh. The patch layer is read at startup, so the running host"
  say "  still has the plugin mounted and will keep executing on the node until"
  say "  it is restarted."
  say ""
  say "  The host's own providers are re-enabled by removing the disable block,"
  say "  so the execution world returns to this machine after the restart."
  say "  If the node was already disconnected, that is the state you were in:"
  say "  every operation refused until the restart takes effect."
  say ""
  if [ -f "$DSH_HOME/node-credential" ]; then
    say "  The generated credential at $DSH_HOME/node-credential was LEFT in"
    say "  place: it is a secret, and deleting secrets is not this script's"
    say "  call. Remove it yourself when nothing else uses it:"
    say ""
    say "      rm -f $DSH_HOME/node-credential"
    say ""
  fi
  return 0
}

# ── node ─────────────────────────────────────────────────────────────────────
uninstall_node() {
  found=0
  is_our_wrapper "$WRAPPER" && found=1
  [ -d "$CACHE_DIR" ] && found=1

  if [ "$found" -eq 0 ]; then
    say "node: nothing installed — skipped"
    return 0
  fi
  [ "$AUTO" -eq 1 ] && say "node:"
  say "[node] removing the dsh-node command and cached source"

  # Only a wrapper WE generated is removed; the signature line is the proof.
  if is_our_wrapper "$WRAPPER"; then
    act "remove $WRAPPER"
    if [ "$DRY_RUN" -eq 0 ]; then rm -f "$WRAPPER"; fi
  elif [ -f "$WRAPPER" ]; then
    say "  !! $WRAPPER exists but was not generated by the installer — left alone."
  fi

  if [ -d "$CACHE_DIR" ]; then
    act "remove $CACHE_DIR (downloaded source)"
    if [ "$DRY_RUN" -eq 0 ]; then rm -rf "$CACHE_DIR"; fi
  fi

  # A running agent would keep executing on this machine. Say so rather than
  # kill it: it may be mid-command, and stopping it is the operator's call.
  if pgrep -f 'agent-cli\.js' >/dev/null 2>&1; then
    say ""
    say "  !! A dsh-node agent is STILL RUNNING on this machine. It holds an open"
    say "  connection to the host and will keep executing commands there until it"
    say "  is stopped:"
    say ""
    say "      pkill -f agent-cli.js"
    say ""
  fi

  # The working directory is the agent's data, not the installer's. Only
  # removed when asked for by name.
  if [ -d "$WORKSPACE_DIR" ]; then
    if [ "$PURGE_WORKSPACE" -eq 1 ]; then
      act "remove $WORKSPACE_DIR (--purge-workspace)"
      if [ "$DRY_RUN" -eq 0 ]; then rm -rf "$WORKSPACE_DIR"; fi
    else
      say "  $WORKSPACE_DIR was left in place: it holds whatever work was done"
      say "  there. Delete it with --purge-workspace if you are sure."
    fi
  fi
  return 0
}

say "deepseek-harness-remote-node uninstaller"
say "  dsh home: $DSH_HOME"
say "  cache:    $CACHE_DIR"
say "  command:  $WRAPPER"
[ "$DRY_RUN" -eq 1 ] && say "  (dry run — nothing will be written)"
say ""

status=0
if [ "$DO_HOST" -eq 1 ]; then uninstall_host || status=1; fi
if [ "$DO_HOST" -eq 1 ] && [ "$DO_NODE" -eq 1 ]; then say ""; fi
if [ "$DO_NODE" -eq 1 ]; then uninstall_node || status=1; fi

say ""
say "[done]"
exit "$status"
